server:
  port: 10200
  
spring:
  application:
    name: persona
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:oracle:thin:@gend-clust-scan.gendarmeria.gob.cl:1521/test.gendarmeria.gob.cl
    username: genchi
    password: prueba
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
